services:
  - type: web
    name: ast-interview
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: ast-interview
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: postgresql
          name: ast-interview-db
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromService:
          type: postgresql
          name: ast-interview-db
          property: database
      - key: DB_USERNAME
        fromService:
          type: postgresql
          name: ast-interview-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: postgresql
          name: ast-interview-db
          property: password

  - type: postgresql
    name: ast-interview-db
    plan: free
    ipAllowList: []
